import React, { useEffect, useState } from 'react';
import { Pencil, Plus, Trash2, Users } from 'lucide-react';
import { pessoaService, type Pessoa } from '../../services/pessoa.service';
import { EmptyState, TableSkeleton } from '../../components/Feedback';
import { useToast } from '../../contexts/ToastContext';

const pessoaVazia = (): Omit<Pessoa, 'id' | 'criado_em'> => ({ pessoa_fisica: true, nome_fantasia: '', cnpj_cpf: '', logradouro: '', numero: '', complemento: '', bairro: '', cidade: '', whatsapp: '', cliente: true, fornecedor: false });

export const TelaClientes: React.FC = () => {
  const [pessoas, setPessoas] = useState<Pessoa[]>([]); const [formulario, setFormulario] = useState(pessoaVazia());
  const [editandoId, setEditandoId] = useState<number | null>(null); const [modalAberto, setModalAberto] = useState(false); const [carregando, setCarregando] = useState(false);
  const { toast } = useToast();
  const carregar = async () => { try { setCarregando(true); setPessoas(await pessoaService.listar()); } catch { toast('Não foi possível carregar as pessoas.', 'error'); } finally { setCarregando(false); } };
  useEffect(() => { carregar(); }, []);
  const abrirNovo = () => { setFormulario(pessoaVazia()); setEditandoId(null); setModalAberto(true); };
  const abrirEdicao = (pessoa: Pessoa) => { const { id, criado_em, ...dados } = pessoa; setFormulario(dados); setEditandoId(id!); setModalAberto(true); };
  const salvar = async (event: React.FormEvent) => { event.preventDefault(); try { if (editandoId) await pessoaService.atualizar(editandoId, formulario); else await pessoaService.cadastrar(formulario); toast('Pessoa salva com sucesso.'); setModalAberto(false); carregar(); } catch (erro: any) { toast(erro.response?.data?.mensagem || 'Não foi possível salvar a pessoa.', 'error'); } };
  const excluir = async (pessoa: Pessoa) => { if (!pessoa.id || !window.confirm(`Excluir ${pessoa.nome_fantasia}?`)) return; try { await pessoaService.excluir(pessoa.id); toast('Pessoa excluída.'); carregar(); } catch (erro: any) { toast(erro.response?.data?.mensagem || 'Não foi possível excluir a pessoa.', 'error'); } };
  const atualizar = <K extends keyof typeof formulario>(campo: K, valor: (typeof formulario)[K]) => setFormulario({ ...formulario, [campo]: valor });

  return <div className="mx-auto max-w-7xl space-y-6 p-6">
    <div className="flex items-center justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Users className="text-red-500" /> Pessoas</h1><p className="text-xs text-slate-500 dark:text-slate-400">Clientes e fornecedores em um único cadastro</p></div><button onClick={abrirNovo} className="flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2 text-sm font-bold text-white"><Plus size={18} /> Nova pessoa</button></div>
    <div className="overflow-x-auto rounded-3xl border border-slate-200 bg-white/80 dark:border-slate-800 dark:bg-slate-900/40"><table className="w-full text-left text-sm"><thead className="border-b border-slate-200 bg-slate-100 text-xs uppercase text-slate-500 dark:border-slate-800 dark:bg-slate-900"><tr><th className="p-4">Nome</th><th className="p-4">Documento</th><th className="p-4">WhatsApp</th><th className="p-4">Cidade</th><th className="p-4">Tipo</th><th className="p-4">Ações</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{carregando ? <TableSkeleton columns={6} /> : !pessoas.length ? <tr><td colSpan={6}><EmptyState title="Nenhuma pessoa cadastrada" description="Cadastre clientes ou fornecedores para começar." /></td></tr> : pessoas.map(pessoa => <tr key={pessoa.id}><td className="p-4 font-semibold">{pessoa.nome_fantasia}<small className="ml-2 text-slate-400">{pessoa.pessoa_fisica ? 'PF' : 'PJ'}</small></td><td className="p-4 font-mono">{pessoa.cnpj_cpf || '-'}</td><td className="p-4">{pessoa.whatsapp || '-'}</td><td className="p-4">{pessoa.cidade || '-'}</td><td className="p-4">{pessoa.cliente && <span className="mr-1 rounded bg-blue-100 px-2 py-1 text-xs text-blue-700">Cliente</span>}{pessoa.fornecedor && <span className="rounded bg-amber-100 px-2 py-1 text-xs text-amber-700">Fornecedor</span>}</td><td className="flex gap-2 p-4"><button onClick={() => abrirEdicao(pessoa)} aria-label="Editar pessoa"><Pencil size={16} /></button><button onClick={() => excluir(pessoa)} className="text-red-600" aria-label="Excluir pessoa"><Trash2 size={16} /></button></td></tr>)}</tbody></table></div>
    {modalAberto && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><form onSubmit={salvar} className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white p-6 text-slate-900 dark:bg-slate-900 dark:text-white"><h2 className="mb-4 text-lg font-bold">{editandoId ? 'Editar pessoa' : 'Nova pessoa'}</h2><div className="grid gap-3 md:grid-cols-2"><label>Nome / Razão social<input required value={formulario.nome_fantasia} onChange={e => atualizar('nome_fantasia', e.target.value)} className="campo" /></label><label>{formulario.pessoa_fisica ? 'CPF' : 'CNPJ'}<input value={formulario.cnpj_cpf || ''} onChange={e => atualizar('cnpj_cpf', e.target.value)} className="campo" /></label><label>WhatsApp<input value={formulario.whatsapp || ''} onChange={e => atualizar('whatsapp', e.target.value)} className="campo" /></label><label>Logradouro<input value={formulario.logradouro || ''} onChange={e => atualizar('logradouro', e.target.value)} className="campo" /></label><label>Número<input value={formulario.numero || ''} onChange={e => atualizar('numero', e.target.value)} className="campo" /></label><label>Complemento<input value={formulario.complemento || ''} onChange={e => atualizar('complemento', e.target.value)} className="campo" /></label><label>Bairro<input value={formulario.bairro || ''} onChange={e => atualizar('bairro', e.target.value)} className="campo" /></label><label>Cidade<input value={formulario.cidade || ''} onChange={e => atualizar('cidade', e.target.value)} className="campo" /></label></div><div className="mt-4 flex flex-wrap gap-5 text-sm"><label><input type="checkbox" checked={formulario.pessoa_fisica} onChange={e => atualizar('pessoa_fisica', e.target.checked)} /> Pessoa física</label><label><input type="checkbox" checked={formulario.cliente} onChange={e => atualizar('cliente', e.target.checked)} /> Cliente</label><label><input type="checkbox" checked={formulario.fornecedor} onChange={e => atualizar('fornecedor', e.target.checked)} /> Fornecedor</label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setModalAberto(false)} className="rounded-xl bg-slate-200 px-4 py-2 dark:bg-slate-700">Cancelar</button><button className="rounded-xl bg-red-600 px-4 py-2 font-bold text-white">Salvar</button></div></form></div>}
  </div>;
};
